using Microsoft.Data.SqlClient;using QuanLyThueSanTheThao.Data;using QuanLyThueSanTheThao.Helpers;
namespace QuanLyThueSanTheThao.Forms.Admin;
public partial class FrmBookingSchedule:Form
{
    public FrmBookingSchedule(){InitializeComponent();AppTheme.Upgrade(this);AppTheme.StyleGrid(grid);AppTheme.StyleSecondary(btnRefresh);AppTheme.StylePrimary(btnComplete);AppTheme.StyleDanger(btnCancel);cboStatus.Items.AddRange(new object[]{"Tất cả","Đã xác nhận","Đang sử dụng","Hoàn thành","Đã hủy"});cboStatus.SelectedIndex=0;dtDate.ValueChanged+=(_,__)=>LoadData();cboStatus.SelectedIndexChanged+=(_,__)=>LoadData();txtSearch.TextChanged+=(_,__)=>LoadData();btnRefresh.Click+=(_,__)=>LoadData();btnComplete.Click+=(_,__)=>SetStatus("Completed");btnCancel.Click+=(_,__)=>SetStatus("Cancelled");Shown+=(_,__)=>LoadData();}
    private int? SelectedId()=>grid.CurrentRow?.Cells["DatSanID"].Value is object v?Convert.ToInt32(v):null;
    private string StatusCode()=>cboStatus.Text switch{"Đã xác nhận"=>"Confirmed","Đang sử dụng"=>"InUse","Hoàn thành"=>"Completed","Đã hủy"=>"Cancelled",_=>""};
    private void LoadData(){var status=StatusCode();grid.DataSource=Db.Query(@"SELECT b.DatSanID,b.MaDatSan [Mã đơn],c.HoTen [Khách hàng],f.TenSan [Sân],ft.TenLoaiSan [Loại sân],b.ThoiGianBatDau [Bắt đầu],b.ThoiGianKetThuc [Kết thúc],b.TongTien [Tổng tiền],CASE b.TrangThai WHEN 'Pending' THEN N'Chờ xác nhận' WHEN 'Confirmed' THEN N'Đã xác nhận' WHEN 'InUse' THEN N'Đang sử dụng' WHEN 'Completed' THEN N'Hoàn thành' WHEN 'Cancelled' THEN N'Đã hủy' ELSE b.TrangThai END [Trạng thái],CASE b.TrangThaiThanhToan WHEN 'Unpaid' THEN N'Chưa thanh toán' WHEN 'PartiallyPaid' THEN N'Thanh toán một phần' WHEN 'Paid' THEN N'Đã thanh toán' ELSE b.TrangThaiThanhToan END [Thanh toán] FROM DatSan b JOIN KhachHang c ON c.KhachHangID=b.KhachHangID JOIN SanTheThao f ON f.SanID=b.SanID JOIN LoaiSan ft ON ft.LoaiSanID=f.LoaiSanID WHERE CAST(b.ThoiGianBatDau AS DATE)=@d AND (@st='' OR b.TrangThai=@st) AND (@s='' OR b.MaDatSan LIKE '%'+@s+'%' OR c.HoTen LIKE N'%'+@s+'%' OR f.TenSan LIKE N'%'+@s+'%') ORDER BY b.ThoiGianBatDau",new SqlParameter("@d",dtDate.Value.Date),new SqlParameter("@st",status),new SqlParameter("@s",txtSearch.Text.Trim()));if(grid.Columns.Contains("DatSanID"))grid.Columns["DatSanID"].Visible=false;}
    private void SetStatus(string status){var id=SelectedId();if(id==null)return;if(status=="Cancelled"&&UiMsg.Ask("Hủy lịch đặt đã chọn?", "Xác nhận")!=DialogResult.Yes)return;Db.Execute("UPDATE DatSan SET TrangThai=@s,NgayCapNhat=SYSDATETIME() WHERE DatSanID=@id",new SqlParameter("@s",status),new SqlParameter("@id",id));LoadData();Toast.Success("Đã cập nhật trạng thái lịch.");}
}
