using Microsoft.Data.SqlClient;using QuanLyThueSanTheThao.Data;using QuanLyThueSanTheThao.Forms.Common;using QuanLyThueSanTheThao.Helpers;using QuanLyThueSanTheThao.Services;
namespace QuanLyThueSanTheThao.Forms.Admin;
public partial class FrmBooking:Form
{
    private readonly bool _customerMode;private readonly BookingService _service=new();private decimal _subtotal,_discount,_total;
    public FrmBooking(bool customerMode=false){_customerMode=customerMode;InitializeComponent();AppTheme.Upgrade(this);AppTheme.StyleSecondary(btnCheck);AppTheme.StylePrimary(btnBook);foreach(var c in new[]{cboCustomer,cboType,cboField,cboVoucher})c.DropDownStyle=ComboBoxStyle.DropDownList;dtDate.Format=DateTimePickerFormat.Short;dtStart.Format=dtEnd.Format=DateTimePickerFormat.Time;dtStart.ShowUpDown=dtEnd.ShowUpDown=true;dtDate.MinDate=DateTime.Today;dtStart.Value=DateTime.Today.AddHours(18);dtEnd.Value=DateTime.Today.AddHours(20);cboType.SelectedIndexChanged+=(_,__)=>LoadAvailableFields();cboCustomer.SelectedIndexChanged+=(_,__)=>LoadVouchers();dtDate.ValueChanged+=(_,__)=>LoadAvailableFields();dtStart.ValueChanged+=(_,__)=>LoadAvailableFields();dtEnd.ValueChanged+=(_,__)=>LoadAvailableFields();cboField.SelectedIndexChanged+=(_,__)=>Recalc();cboVoucher.SelectedIndexChanged+=(_,__)=>Recalc();btnCheck.Click+=(_,__)=>LoadAvailableFields();btnBook.Click+=(_,__)=>Book();Shown+=(_,__)=>LoadLookups();}
    private DateTime Start=>dtDate.Value.Date+dtStart.Value.TimeOfDay;private DateTime End=>dtDate.Value.Date+dtEnd.Value.TimeOfDay;
    private void LoadLookups(){try{var customers=Db.Query("SELECT KhachHangID,MaKhachHang+' - '+HoTen TenHienThi FROM KhachHang WHERE DangHoatDong=1 ORDER BY HoTen");cboCustomer.DataSource=customers;cboCustomer.ValueMember="KhachHangID";cboCustomer.DisplayMember="TenHienThi";if(_customerMode){cboCustomer.SelectedValue=SessionContext.CustomerId??0;cboCustomer.Enabled=false;}var types=Db.Query("SELECT LoaiSanID,TenLoaiSan FROM LoaiSan WHERE DangHoatDong=1 ORDER BY TenLoaiSan");cboType.DataSource=types;cboType.ValueMember="LoaiSanID";cboType.DisplayMember="TenLoaiSan";LoadVouchers();LoadAvailableFields();}catch(Exception ex){UiMsg.Error(ex.Message);}}
    private void LoadVouchers(){if(cboCustomer.SelectedValue==null)return;var cid=Convert.ToInt32(cboCustomer.SelectedValue);var dt=Db.Query(@"SELECT CAST(NULL AS INT) PhieuGiamGiaID,N'Không dùng voucher' TenHienThi UNION ALL SELECT v.PhieuGiamGiaID,v.MaPhieuGiamGia+' - '+v.TenPhieuGiamGia FROM PhieuGiamGia v JOIN PhieuGiamGiaKhachHang cv ON cv.PhieuGiamGiaID=v.PhieuGiamGiaID WHERE cv.KhachHangID=@c AND cv.DaSuDung=0 AND v.DangHoatDong=1 AND SYSDATETIME() BETWEEN v.NgayBatDau AND v.NgayKetThuc ORDER BY TenHienThi",new SqlParameter("@c",cid));cboVoucher.DataSource=dt;cboVoucher.ValueMember="PhieuGiamGiaID";cboVoucher.DisplayMember="TenHienThi";}
    private void LoadAvailableFields(){if(cboType.SelectedValue==null||End<=Start){lblAvailability.Text="Giờ kết thúc phải sau giờ bắt đầu.";return;}try{var dt=_service.GetAvailableFields(Start,End,Convert.ToInt32(cboType.SelectedValue));cboField.DataSource=dt;cboField.ValueMember="SanID";cboField.DisplayMember="TenSan";lblAvailability.Text=dt.Rows.Count>0?$"Có {dt.Rows.Count} sân trống trong khung giờ này.":"Không còn sân trống.";Recalc();}catch(Exception ex){lblAvailability.Text=ex.Message;}}
    private void Recalc(){if(cboField.SelectedValue==null||End<=Start){_subtotal=_discount=_total=0;ShowAmounts();return;}try{var rate=Convert.ToDecimal(((System.Data.DataRowView)cboField.SelectedItem).Row["GiaMoiGio"]);_subtotal=Math.Round(rate*(decimal)(End-Start).TotalHours);_discount=0;var promo=Db.Query("SELECT TOP 1 PhanTramGiam FROM KhuyenMai WHERE DangHoatDong=1 AND SYSDATETIME() BETWEEN NgayBatDau AND NgayKetThuc ORDER BY PhanTramGiam DESC,KhuyenMaiID DESC");if(promo.Rows.Count>0)_discount=Math.Round(_subtotal*Convert.ToDecimal(promo.Rows[0]["PhanTramGiam"])/100m);if(cboVoucher.SelectedValue!=null&&cboVoucher.SelectedValue!=DBNull.Value){var v=Db.Query("SELECT LoaiGiamGia,GiaTriGiam,MucGiamToiDa,DonToiThieu FROM PhieuGiamGia WHERE PhieuGiamGiaID=@id",new SqlParameter("@id",Convert.ToInt32(cboVoucher.SelectedValue)));if(v.Rows.Count>0&&_subtotal>=Convert.ToDecimal(v.Rows[0]["DonToiThieu"])){var r=v.Rows[0];var baseAfterPromo=Math.Max(0,_subtotal-_discount);var vd=Convert.ToString(r["LoaiGiamGia"])=="Percent"?baseAfterPromo*Convert.ToDecimal(r["GiaTriGiam"])/100m:Convert.ToDecimal(r["GiaTriGiam"]);if(r["MucGiamToiDa"]!=DBNull.Value)vd=Math.Min(vd,Convert.ToDecimal(r["MucGiamToiDa"]));_discount+=Math.Min(vd,baseAfterPromo);}}_total=_subtotal-_discount;ShowAmounts(rate);}catch{}}
    private void ShowAmounts(decimal rate=0){lblPrice.Text="Đơn giá: "+rate.ToString("N0")+" đ/giờ";lblSubtotal.Text="Tiền sân: "+_subtotal.ToString("N0")+" đ";lblDiscount.Text="Giảm giá: -"+_discount.ToString("N0")+" đ";lblTotal.Text="Cần thanh toán: "+_total.ToString("N0")+" đ";}
    private void Book(){if(cboCustomer.SelectedValue==null||cboField.SelectedValue==null){UiMsg.Warn("Vui lòng chọn khách hàng và sân.");return;}if(End<=Start||Start<DateTime.Now.AddMinutes(-1)){UiMsg.Warn("Thời gian đặt không hợp lệ.");return;}try{int? voucher=null;if(cboVoucher.SelectedValue!=null&&cboVoucher.SelectedValue!=DBNull.Value)voucher=Convert.ToInt32(cboVoucher.SelectedValue);var id=_service.CreateBooking(Convert.ToInt32(cboCustomer.SelectedValue),Convert.ToInt32(cboField.SelectedValue),Start,End,voucher,txtNote.Text.Trim(),SessionContext.UserId);Toast.Success("Đặt sân thành công. Mã đơn: DS"+id.ToString("000000"));using var pay=new FrmPayment(id);pay.ShowDialogFx(this);LoadAvailableFields();}catch(Exception ex){UiMsg.Warn(ex.Message, "Đặt sân");}}
}
