using Microsoft.Data.SqlClient;using QuanLyThueSanTheThao.Data;using QuanLyThueSanTheThao.Helpers;
namespace QuanLyThueSanTheThao.Forms.Admin;
public partial class FrmCustomers:Form
{
    private int? _id;
    public FrmCustomers(){InitializeComponent();AppTheme.StyleGrid(grid);AppTheme.StyleSecondary(btnRefresh);AppTheme.StyleSecondary(btnNew);AppTheme.StylePrimary(btnSave);AppTheme.StyleDanger(btnDelete);grid.SelectionChanged+=(_,__)=>Bind();txtSearch.TextChanged+=(_,__)=>LoadData();btnRefresh.Click+=(_,__)=>LoadData();btnNew.Click+=(_,__)=>ClearForm();btnSave.Click+=(_,__)=>Save();btnDelete.Click+=(_,__)=>Delete();Shown+=(_,__)=>LoadData();}
    private void LoadData(){grid.DataSource=Db.Query(@"SELECT KhachHangID,MaKhachHang [Mã KH],HoTen [Họ tên],SoDienThoai [SĐT],Email,DiaChi [Địa chỉ],NgaySinh [Ngày sinh],DiemTichLuy [Điểm],DangHoatDong [Hoạt động] FROM KhachHang WHERE @s='' OR MaKhachHang LIKE '%'+@s+'%' OR HoTen LIKE N'%'+@s+'%' OR SoDienThoai LIKE '%'+@s+'%' ORDER BY KhachHangID DESC",new SqlParameter("@s",txtSearch.Text.Trim()));if(grid.Columns.Contains("KhachHangID"))grid.Columns["KhachHangID"].Visible=false;}
    private void Bind(){if(grid.CurrentRow?.DataBoundItem is not System.Data.DataRowView rv)return;var r=rv.Row;_id=Convert.ToInt32(r["KhachHangID"]);txtCode.Text=Convert.ToString(r["Mã KH"]);txtName.Text=Convert.ToString(r["Họ tên"]);txtPhone.Text=Convert.ToString(r["SĐT"]);txtEmail.Text=Convert.ToString(r["Email"]);txtAddress.Text=Convert.ToString(r["Địa chỉ"]);if(r["Ngày sinh"]!=DBNull.Value)dtBirth.Value=Convert.ToDateTime(r["Ngày sinh"]);chkActive.Checked=Convert.ToBoolean(r["Hoạt động"]);}
    private void ClearForm(){_id=null;txtCode.Text="KH"+DateTime.Now.ToString("HHmmss");txtName.Clear();txtPhone.Clear();txtEmail.Clear();txtAddress.Clear();dtBirth.Value=DateTime.Today.AddYears(-18);chkActive.Checked=true;txtName.Focus();}
    private void Save(){if(string.IsNullOrWhiteSpace(txtCode.Text)||string.IsNullOrWhiteSpace(txtName.Text)){MessageBox.Show("Nhập mã khách và họ tên.");return;}var p=new[]{new SqlParameter("@c",txtCode.Text.Trim()),new SqlParameter("@n",txtName.Text.Trim()),new SqlParameter("@p",txtPhone.Text.Trim()),new SqlParameter("@e",txtEmail.Text.Trim()),new SqlParameter("@a",txtAddress.Text.Trim()),new SqlParameter("@d",dtBirth.Value.Date),new SqlParameter("@x",chkActive.Checked)};if(_id==null)Db.Execute("INSERT INTO KhachHang(MaKhachHang,HoTen,SoDienThoai,Email,DiaChi,NgaySinh,DangHoatDong) VALUES(@c,@n,@p,@e,@a,@d,@x)",p);else{var l=p.ToList();l.Add(new SqlParameter("@id",_id));Db.Execute("UPDATE KhachHang SET MaKhachHang=@c,HoTen=@n,SoDienThoai=@p,Email=@e,DiaChi=@a,NgaySinh=@d,DangHoatDong=@x WHERE KhachHangID=@id",l.ToArray());}LoadData();}
    private void Delete(){if(_id==null||MessageBox.Show("Xóa khách hàng này?","Xác nhận",MessageBoxButtons.YesNo)!=DialogResult.Yes)return;try{Db.Execute("DELETE FROM KhachHang WHERE KhachHangID=@id AND TaiKhoanID IS NULL",new SqlParameter("@id",_id));ClearForm();LoadData();}catch(Exception ex){MessageBox.Show("Không thể xóa khách đã có tài khoản hoặc lịch sử giao dịch. Có thể khóa trạng thái.\n"+ex.Message);}}
}
