#nullable enable
namespace QuanLyThueSanTheThao.Forms.Admin;
partial class FrmFields
{
    private System.ComponentModel.IContainer? components=null;private SplitContainer split=null!;private DataGridView grid=null!;private TextBox txtSearch=null!,txtCode=null!,txtName=null!,txtDesc=null!,txtLocation=null!,txtPrice=null!;private ComboBox cboType=null!,cboStatus=null!;private CheckBox chkActive=null!;private Button btnRefresh=null!,btnNew=null!,btnSave=null!,btnDelete=null!;
    protected override void Dispose(bool disposing){if(disposing&&components!=null)components.Dispose();base.Dispose(disposing);}
    private void InitializeComponent(){split=new SplitContainer();grid=new DataGridView();txtSearch=new TextBox();txtCode=new TextBox();txtName=new TextBox();txtDesc=new TextBox();txtLocation=new TextBox();txtPrice=new TextBox();cboType=new ComboBox();cboStatus=new ComboBox();chkActive=new CheckBox();btnRefresh=new Button();btnNew=new Button();btnSave=new Button();btnDelete=new Button();SuspendLayout();
        split.Dock=DockStyle.Fill;split.Size=new Size(1180,720);split.FixedPanel=FixedPanel.Panel2;split.SplitterDistance=820;split.Panel1.Padding=new Padding(8);split.Panel2.Padding=new Padding(16);split.Panel2.BackColor=Color.White;
        var top=new Panel{Dock=DockStyle.Top,Height=48};txtSearch.PlaceholderText="Tìm sân...";txtSearch.Location=new Point(0,8);txtSearch.Width=260;btnRefresh.Text="Làm mới";btnRefresh.Location=new Point(270,6);btnRefresh.Size=new Size(90,34);top.Controls.AddRange(new Control[]{txtSearch,btnRefresh});grid.Dock=DockStyle.Fill;split.Panel1.Controls.Add(grid);split.Panel1.Controls.Add(top);
        var y=16;var title=new Label{Text="Thông tin sân",Font=new Font("Segoe UI Semibold",13F,FontStyle.Bold),AutoSize=true,Location=new Point(16,y)};y+=48;
        Control[] Add(string label,Control c){var l=new Label{Text=label,AutoSize=true,Location=new Point(16,y)};c.Location=new Point(16,y+23);c.Width=285;y+=63;split.Panel2.Controls.Add(l);split.Panel2.Controls.Add(c);return new[]{l,c};}
        split.Panel2.Controls.Add(title);Add("Mã sân",txtCode);Add("Tên sân",txtName);Add("Loại sân",cboType);Add("Vị trí",txtLocation);Add("Giá / giờ",txtPrice);Add("Trạng thái",cboStatus);Add("Mô tả",txtDesc);txtDesc.Multiline=true;txtDesc.Height=58;y+=34;chkActive.Text="Đang hoạt động";chkActive.AutoSize=true;chkActive.Location=new Point(16,y);y+=42;btnNew.Text="Mới";btnSave.Text="Lưu";btnDelete.Text="Xóa";btnNew.Location=new Point(16,y);btnSave.Location=new Point(111,y);btnDelete.Location=new Point(206,y);foreach(var b in new[]{btnNew,btnSave,btnDelete})b.Size=new Size(85,38);split.Panel2.Controls.AddRange(new Control[]{chkActive,btnNew,btnSave,btnDelete});Controls.Add(split);BackColor=Color.FromArgb(243,249,248);ResumeLayout(false);}
}
