#nullable enable
namespace QuanLyThueSanTheThao.Forms.Admin;
partial class FrmFieldTypes
{
    private System.ComponentModel.IContainer? components=null;private SplitContainer split=null!;private DataGridView grid=null!;private TextBox txtSearch=null!;private Button btnRefresh=null!;private TextBox txtCode=null!,txtName=null!,txtDesc=null!;private CheckBox chkActive=null!;private Button btnNew=null!,btnSave=null!,btnDelete=null!;
    protected override void Dispose(bool disposing){if(disposing&&components!=null)components.Dispose();base.Dispose(disposing);}
    private void InitializeComponent(){split=new SplitContainer();grid=new DataGridView();txtSearch=new TextBox();btnRefresh=new Button();txtCode=new TextBox();txtName=new TextBox();txtDesc=new TextBox();chkActive=new CheckBox();btnNew=new Button();btnSave=new Button();btnDelete=new Button();SuspendLayout();
        split.Dock=DockStyle.Fill;split.Size=new Size(1180,720);split.FixedPanel=FixedPanel.Panel2;split.SplitterDistance=840;split.Panel1.Padding=new Padding(8);split.Panel2.Padding=new Padding(16);split.Panel2.BackColor=Color.White;
        var top=new Panel{Dock=DockStyle.Top,Height=48};txtSearch.PlaceholderText="Tìm loại sân...";txtSearch.Location=new Point(0,8);txtSearch.Width=260;btnRefresh.Text="Làm mới";btnRefresh.Location=new Point(270,6);btnRefresh.Size=new Size(90,34);top.Controls.AddRange(new Control[]{txtSearch,btnRefresh});grid.Dock=DockStyle.Fill;split.Panel1.Controls.Add(grid);split.Panel1.Controls.Add(top);
        var title=new Label{Text="Thông tin loại sân",Font=new Font("Segoe UI Semibold",13F,FontStyle.Bold),AutoSize=true,Location=new Point(16,16)};var l1=new Label{Text="Mã loại",AutoSize=true,Location=new Point(16,62)};txtCode.Location=new Point(16,86);txtCode.Width=260;var l2=new Label{Text="Tên loại sân",AutoSize=true,Location=new Point(16,126)};txtName.Location=new Point(16,150);txtName.Width=260;var l3=new Label{Text="Mô tả",AutoSize=true,Location=new Point(16,190)};txtDesc.Location=new Point(16,214);txtDesc.Width=260;txtDesc.Height=78;txtDesc.Multiline=true;chkActive.Text="Đang hoạt động";chkActive.Location=new Point(16,306);chkActive.AutoSize=true;btnNew.Text="Mới";btnNew.Location=new Point(16,352);btnSave.Text="Lưu";btnSave.Location=new Point(106,352);btnDelete.Text="Xóa";btnDelete.Location=new Point(196,352);foreach(var b in new[]{btnNew,btnSave,btnDelete})b.Size=new Size(80,38);split.Panel2.Controls.AddRange(new Control[]{title,l1,txtCode,l2,txtName,l3,txtDesc,chkActive,btnNew,btnSave,btnDelete});Controls.Add(split);BackColor=Color.FromArgb(243,249,248);ResumeLayout(false);}
}
