using Microsoft.Data.SqlClient;using QuanLyThueSanTheThao.Data;using QuanLyThueSanTheThao.Helpers;
namespace QuanLyThueSanTheThao.Forms.Admin;
public partial class FrmVouchers:Form
{
    private int? _id;
    public FrmVouchers(){InitializeComponent();AppTheme.StyleGrid(grid);AppTheme.StyleSecondary(btnRefresh);AppTheme.StyleSecondary(btnNew);AppTheme.StylePrimary(btnSave);AppTheme.StyleDanger(btnDelete);AppTheme.StyleSecondary(btnAssign);cboType.Items.AddRange(new object[]{"Percent","Fixed"});cboType.DropDownStyle=ComboBoxStyle.DropDownList;cboType.SelectedIndex=0;grid.SelectionChanged+=(_,__)=>Bind();txtSearch.TextChanged+=(_,__)=>LoadData();btnRefresh.Click+=(_,__)=>LoadData();btnNew.Click+=(_,__)=>Clear();btnSave.Click+=(_,__)=>Save();btnDelete.Click+=(_,__)=>Delete();btnAssign.Click+=(_,__)=>Assign();Shown+=(_,__)=>LoadData();}
    private void LoadData(){grid.DataSource=Db.Query(@"SELECT PhieuGiamGiaID,MaPhieuGiamGia [Mã],TenPhieuGiamGia [Tên],LoaiGiamGia [Loại],GiaTriGiam [Giá trị],MucGiamToiDa [Tối đa],DonToiThieu [Đơn tối thiểu],NgayBatDau [Bắt đầu],NgayKetThuc [Kết thúc],SoLuong [SL],DangHoatDong [Hoạt động] FROM PhieuGiamGia WHERE @s='' OR MaPhieuGiamGia LIKE '%'+@s+'%' OR TenPhieuGiamGia LIKE N'%'+@s+'%' ORDER BY PhieuGiamGiaID DESC",new SqlParameter("@s",txtSearch.Text.Trim()));if(grid.Columns.Contains("PhieuGiamGiaID"))grid.Columns["PhieuGiamGiaID"].Visible=false;}
    private void Bind(){if(grid.CurrentRow?.DataBoundItem is not System.Data.DataRowView rv)return;var r=rv.Row;_id=Convert.ToInt32(r["PhieuGiamGiaID"]);txtCode.Text=Convert.ToString(r["Mã"]);txtName.Text=Convert.ToString(r["Tên"]);cboType.SelectedItem=Convert.ToString(r["Loại"]);txtValue.Text=Convert.ToDecimal(r["Giá trị"]).ToString("0.##");txtMax.Text=r["Tối đa"]==DBNull.Value?"":Convert.ToDecimal(r["Tối đa"]).ToString("0");txtMin.Text=Convert.ToDecimal(r["Đơn tối thiểu"]).ToString("0");txtQty.Text=r["SL"]==DBNull.Value?"":Convert.ToString(r["SL"]);dtStart.Value=Convert.ToDateTime(r["Bắt đầu"]);dtEnd.Value=Convert.ToDateTime(r["Kết thúc"]);chkActive.Checked=Convert.ToBoolean(r["Hoạt động"]);}
    private void Clear(){_id=null;txtCode.Clear();txtName.Clear();txtValue.Text="10";txtMax.Clear();txtMin.Text="0";txtQty.Text="100";dtStart.Value=DateTime.Now;dtEnd.Value=DateTime.Now.AddMonths(1);chkActive.Checked=true;}
    private void Save(){if(string.IsNullOrWhiteSpace(txtCode.Text)||string.IsNullOrWhiteSpace(txtName.Text)||!decimal.TryParse(txtValue.Text,out var val)||!decimal.TryParse(txtMin.Text,out var min)){MessageBox.Show("Thông tin voucher chưa hợp lệ.");return;}decimal? max=decimal.TryParse(txtMax.Text,out var mx)?mx:null;int? qty=int.TryParse(txtQty.Text,out var q)?q:null;var p=new[]{new SqlParameter("@c",txtCode.Text.Trim()),new SqlParameter("@n",txtName.Text.Trim()),new SqlParameter("@t",cboType.Text),new SqlParameter("@v",val),new SqlParameter("@m",(object?)max??DBNull.Value),new SqlParameter("@min",min),new SqlParameter("@s",dtStart.Value),new SqlParameter("@e",dtEnd.Value),new SqlParameter("@q",(object?)qty??DBNull.Value),new SqlParameter("@a",chkActive.Checked)};if(_id==null)Db.Execute("INSERT INTO PhieuGiamGia(MaPhieuGiamGia,TenPhieuGiamGia,LoaiGiamGia,GiaTriGiam,MucGiamToiDa,DonToiThieu,NgayBatDau,NgayKetThuc,SoLuong,DangHoatDong) VALUES(@c,@n,@t,@v,@m,@min,@s,@e,@q,@a)",p);else{var l=p.ToList();l.Add(new SqlParameter("@id",_id));Db.Execute("UPDATE PhieuGiamGia SET MaPhieuGiamGia=@c,TenPhieuGiamGia=@n,LoaiGiamGia=@t,GiaTriGiam=@v,MucGiamToiDa=@m,DonToiThieu=@min,NgayBatDau=@s,NgayKetThuc=@e,SoLuong=@q,DangHoatDong=@a WHERE PhieuGiamGiaID=@id",l.ToArray());}LoadData();}
    private void Delete(){if(_id==null||MessageBox.Show("Xóa voucher?","Xác nhận",MessageBoxButtons.YesNo)!=DialogResult.Yes)return;try{Db.Execute("DELETE FROM PhieuGiamGia WHERE PhieuGiamGiaID=@id",new SqlParameter("@id",_id));Clear();LoadData();}catch(Exception ex){MessageBox.Show("Voucher đã được sử dụng/cấp cho khách nên không thể xóa. Có thể tắt hoạt động.\n"+ex.Message);}}
    private void Assign(){if(_id==null){MessageBox.Show("Chọn voucher cần cấp.");return;}using var f=new Form{Text="Cấp voucher cho khách",StartPosition=FormStartPosition.CenterParent,Size=new Size(430,190),FormBorderStyle=FormBorderStyle.FixedDialog,MaximizeBox=false,MinimizeBox=false};var combo=new ComboBox{Left=20,Top=30,Width=370,DropDownStyle=ComboBoxStyle.DropDownList};var dt=Db.Query("SELECT KhachHangID,MaKhachHang+' - '+HoTen TenHienThi FROM KhachHang WHERE DangHoatDong=1 ORDER BY HoTen");combo.DataSource=dt;combo.ValueMember="KhachHangID";combo.DisplayMember="TenHienThi";var b=new Button{Text="Cấp voucher",Left=250,Top=90,Width=140,Height=38};AppTheme.StylePrimary(b);b.Click+=(_,__)=>{if(combo.SelectedValue==null)return;try{Db.Execute("IF NOT EXISTS(SELECT 1 FROM PhieuGiamGiaKhachHang WHERE KhachHangID=@c AND PhieuGiamGiaID=@v) INSERT INTO PhieuGiamGiaKhachHang(KhachHangID,PhieuGiamGiaID) VALUES(@c,@v)",new SqlParameter("@c",Convert.ToInt32(combo.SelectedValue)),new SqlParameter("@v",_id));MessageBox.Show("Đã cấp voucher.");f.Close();}catch(Exception ex){MessageBox.Show(ex.Message);}};f.Controls.AddRange(new Control[]{combo,b});f.ShowDialog(this);}
}
