using QuanLyThueSanTheThao.Helpers;using QuanLyThueSanTheThao.Services;
namespace QuanLyThueSanTheThao.Forms.Common;
public partial class FrmPayment:Form
{
    private readonly int _bookingId;private readonly PaymentService _payment=new();private readonly SettingsService _settings=new();private int _invoiceId;private decimal _amount;private string _bookingCode="";
    public FrmPayment(int bookingId){_bookingId=bookingId;InitializeComponent();AppTheme.StylePrimary(btnConfirm);AppTheme.StyleSecondary(btnClose);cboMethod.Items.AddRange(new object[]{"Tiền mặt","QR chuyển khoản","Chuyển khoản","Chưa thanh toán"});cboMethod.SelectedIndex=SessionContext.Role=="Customer"?1:0;cboMethod.SelectedIndexChanged+=(_,__)=>RenderMethod();btnConfirm.Click+=(_,__)=>Confirm();btnClose.Click+=(_,__)=>Close();Shown+=(_,__)=>LoadInfo();}
    private void LoadInfo(){try{var r=_payment.GetPaymentInfo(_bookingId);_invoiceId=Convert.ToInt32(r["HoaDonID"]);_amount=Convert.ToDecimal(r["TongTien"])-Convert.ToDecimal(r["SoTienDaTra"]);_bookingCode=Convert.ToString(r["MaDatSan"])??"";lblBooking.Text=$"{_bookingCode} • {r["TenSan"]} • {Convert.ToDateTime(r["ThoiGianBatDau"]):dd/MM HH:mm} - {Convert.ToDateTime(r["ThoiGianKetThuc"]):HH:mm}";lblAmount.Text=_amount.ToString("N0")+" đ";RenderMethod();}catch(Exception ex){MessageBox.Show(ex.Message);Close();}}
    private void RenderMethod(){var show=cboMethod.SelectedIndex==1||cboMethod.SelectedIndex==2;pnlQr.Visible=show;if(!show)return;try{var bank=_settings.Get("BankName","TECHCOMBANK");var bin=_settings.Get("BankBin","970407");var acc=_settings.Get("BankAccountNumber","");var name=_settings.Get("BankAccountName","");var prefix=_settings.Get("QrTransferPrefix","THANHTOAN");var content=$"{prefix} {_bookingCode}";lblBank.Text="Ngân hàng: "+bank;lblAccount.Text="Số tài khoản: "+acc;lblAccountName.Text="Chủ tài khoản: "+name;lblContent.Text="Nội dung: "+content;picQr.Image?.Dispose();picQr.Image=QrImageHelper.Create(VietQrPayloadBuilder.Build(bin,acc,_amount,content),6);}catch(Exception ex){picQr.Image=null;lblContent.Text="Chưa thể tạo QR: "+ex.Message;}}
    private void Confirm(){if(_amount<=0){MessageBox.Show("Hóa đơn đã thanh toán đủ.");return;}var selected=cboMethod.Text;string method=selected switch{"Tiền mặt"=>"Cash","QR chuyển khoản"=>"QR","Chuyển khoản"=>"BankTransfer",_=>"Unpaid"};if(method=="Unpaid"){Close();return;}var isStaff=SessionContext.Role is "Admin" or "Employee";var confirmPaid=method=="Cash"&&isStaff;if(method is "QR" or "BankTransfer")confirmPaid=false;try{_payment.RecordPayment(_invoiceId,_amount,method,txtReference.Text.Trim(),confirmPaid);if(confirmPaid)MessageBox.Show("Đã ghi nhận thanh toán thành công.");else MessageBox.Show("Đã ghi nhận yêu cầu thanh toán. Chuyển khoản/QR sẽ ở trạng thái chờ xác nhận cho đến khi nhân viên xác nhận tiền về.");DialogResult=DialogResult.OK;Close();}catch(Exception ex){MessageBox.Show(ex.Message,"Thanh toán",MessageBoxButtons.OK,MessageBoxIcon.Error);}}
}
