using Microsoft.Data.SqlClient;using QuanLyThueSanTheThao.Data;using QuanLyThueSanTheThao.Helpers;
namespace QuanLyThueSanTheThao.Forms.Customer;
public partial class FrmCustomerProfile:Form
{
    public FrmCustomerProfile(){InitializeComponent();AppTheme.Upgrade(this);AppTheme.StylePrimary(btnSave);AppTheme.StyleSecondary(btnChangePassword);btnSave.Click+=(_,__)=>Save();btnChangePassword.Click+=(_,__)=>ChangePassword();Shown+=(_,__)=>LoadData();}
    private void LoadData(){var dt=Db.Query("SELECT MaKhachHang,HoTen,SoDienThoai,Email,DiaChi,NgaySinh,DiemTichLuy FROM KhachHang WHERE KhachHangID=@id",new SqlParameter("@id",SessionContext.CustomerId??0));if(dt.Rows.Count==0)return;var r=dt.Rows[0];txtCode.Text=Convert.ToString(r["MaKhachHang"]);txtName.Text=Convert.ToString(r["HoTen"]);txtPhone.Text=Convert.ToString(r["SoDienThoai"]);txtEmail.Text=Convert.ToString(r["Email"]);txtAddress.Text=Convert.ToString(r["DiaChi"]);if(r["NgaySinh"]!=DBNull.Value)dtBirth.Value=Convert.ToDateTime(r["NgaySinh"]);lblPoints.Text="Điểm tích lũy: "+Convert.ToString(r["DiemTichLuy"]);}
    private void Save(){if(string.IsNullOrWhiteSpace(txtName.Text)){UiMsg.Warn("Họ tên không được để trống.");return;}Db.Execute("UPDATE KhachHang SET HoTen=@n,SoDienThoai=@p,Email=@e,DiaChi=@a,NgaySinh=@d WHERE KhachHangID=@id",new SqlParameter("@n",txtName.Text.Trim()),new SqlParameter("@p",txtPhone.Text.Trim()),new SqlParameter("@e",txtEmail.Text.Trim()),new SqlParameter("@a",txtAddress.Text.Trim()),new SqlParameter("@d",dtBirth.Value.Date),new SqlParameter("@id",SessionContext.CustomerId??0));SessionContext.FullName=txtName.Text.Trim();Toast.Success("Đã cập nhật thông tin.");}
    private void ChangePassword(){using var f=new Form{Text="Đổi mật khẩu",StartPosition=FormStartPosition.CenterParent,Size=new Size(430,260),FormBorderStyle=FormBorderStyle.FixedDialog,MaximizeBox=false,MinimizeBox=false};var oldP=new TextBox{Left=25,Top=30,Width=360,PlaceholderText="Mật khẩu hiện tại",UseSystemPasswordChar=true};var newP=new TextBox{Left=25,Top=75,Width=360,PlaceholderText="Mật khẩu mới",UseSystemPasswordChar=true};var confirm=new TextBox{Left=25,Top=120,Width=360,PlaceholderText="Nhập lại mật khẩu mới",UseSystemPasswordChar=true};var b=new Button{Left=235,Top=170,Width=150,Height=38,Text="Đổi mật khẩu"};AppTheme.StylePrimary(b);b.Click+=(_,__)=>{var dt=Db.Query("SELECT MatKhauBam,MuoiMatKhau FROM TaiKhoan WHERE TaiKhoanID=@id",new SqlParameter("@id",SessionContext.UserId));if(dt.Rows.Count==0)return;var salt=Convert.ToString(dt.Rows[0]["MuoiMatKhau"])??"";if(!string.Equals(Convert.ToString(dt.Rows[0]["MatKhauBam"]),PasswordHelper.Hash(salt,oldP.Text),StringComparison.OrdinalIgnoreCase)){UiMsg.Warn("Mật khẩu hiện tại không đúng.");return;}if(newP.Text.Length<6||newP.Text!=confirm.Text){UiMsg.Warn("Mật khẩu mới tối thiểu 6 ký tự và phải nhập lại chính xác.");return;}var ns=Guid.NewGuid().ToString("N")[..8].ToUpperInvariant();Db.Execute("UPDATE TaiKhoan SET MuoiMatKhau=@s,MatKhauBam=@h WHERE TaiKhoanID=@id",new SqlParameter("@s",ns),new SqlParameter("@h",PasswordHelper.Hash(ns,newP.Text)),new SqlParameter("@id",SessionContext.UserId));Toast.Success("Đã đổi mật khẩu.");f.Close();};f.Controls.AddRange(new Control[]{oldP,newP,confirm,b});AppTheme.Upgrade(f);f.ShowDialogFx(this);}
}
